### ISSUE TITLE
transport: Error while dialing: dial tcp :10017: connect: connection refused

### ISSUE THREAD

**Issue by dexterhahaha** [streamingfast/firehose-core#73]
16|firehose-substreams-tier1  | {"severity":"INFO","timestamp":"2025-01-30T10:03:51.824547285Z","logger":"substreams-tier1.tier1","message":"launching remote worker","trace_id":"73f818e709a9adb39af4950d2a0f65b0","segment":317313,"stage":0,"output_module":"block_database_changes","attempt":12,"execution_timeouts":0,"previous_error":"getting block stream: rpc error: code = Unavailable desc = last connection error: connection error: desc = \"transport: Error while dialing: dial tcp :10017: connect: connection refused\"","logging.googleapis.com/labels":{}}

my config 
```
start:
  args:
    - firehose
    - substreams-tier1
    - substreams-tier2
  flags:
    common-first-streamable-block: $common_first_streamable_block
    common-live-blocks-addr: localhost:10014
    advertise-chain-name: solana
    substreams-tier1-block-type: sf.solana.type.v1.Block
    substreams-tier1-grpc-listen-addr: :19000
```
